---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(name)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/info.log
    mode: w
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: logs/error.log
    mode: w
    encoding: utf8
  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/debug.log
    mode: w
    encoding: utf8
root:
  level: DEBUG
  handlers:
    - console
    - info_file_handler
    - error_file_handler
loggers:
  kgworkflow.util.helper:
    level: DEBUG
    handlers:
      - console
      - debug_file_handler
      - info_file_handler
      - error_file_handler
    propagate: no