version: '3'

dotenv: ['.env']

tasks:
  default:
    cmds:
      - echo "Hello world!"

  hermit:
    sources:
      - test/resources/ttl/toy.ttl
      # You can add Python and bash files too.
    generates:
      - output/toy-inferred.ttl
    cmds:
      - | 
        robot reason \
        --input test/resources/ttl/toy.ttl \
        --create-new-ontology true \
        --equivalent-classes-allowed all \
        --axiom-generators "SubClass EquivalentClass DisjointClasses ClassAssertion PropertyAssertion" \
        --output output/toy-inferred.ttl \
        --include-indirect true \
        --reasoner hermit
