version: '3'

dotenv: ['.env']

tasks:
  default:
    cmds:
      - echo "Hello world!"
    silent: true

  infer-toy:
    sources:
      - test/resources/ttl/toy.ttl
      # You can add Python and bash files too.
    generates:
      - output/toy-inferred.ttl
    cmds:
      - just hermit-instance-profile test/resources/ttl/toy.ttl output/toy-inferred.ttl
